/**
 * Vendors the motion runtime into codegen: exported projects ship
 * packages/runtime/src/motion.tsx verbatim as src/motion.tsx.
 *
 *   node scripts/sync-runtime.mjs
 *
 * Run after every change to the runtime; a codegen test fails when they drift.
 */
import { readFile, writeFile } from 'node:fs/promises'

const source = await readFile(new URL('../packages/runtime/src/motion.tsx', import.meta.url), 'utf8')
const output = `/* Generated by scripts/sync-runtime.mjs from packages/runtime/src/motion.tsx. Do not edit. */

export const MOTION_RUNTIME: string = ${JSON.stringify(source)}
`
await writeFile(new URL('../packages/codegen/src/runtime.generated.ts', import.meta.url), output)
console.log(`wrote packages/codegen/src/runtime.generated.ts (${source.length} chars)`)
