/**
 * Vendors shadcn/ui (MIT) component sources from the official registry into
 * packages/library/src/shadcn/registry.generated.ts, rewriting registry import
 * aliases to the paths used in exported projects.
 *
 *   node scripts/sync-shadcn.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises'

const BASE = 'https://ui.shadcn.com/r/styles/new-york-v4'
// `utils` (the cn helper) is a registry placeholder; the exporter writes it directly.
const ITEMS = [
  'button',
  'badge',
  'input',
  'textarea',
  'checkbox',
  'switch',
  'label',
  'avatar',
  'card',
  'alert',
  'progress',
  'separator',
]

function targetPath(registryPath) {
  const file = registryPath.split('/').pop()
  return registryPath.includes('/lib/') ? `src/lib/${file}` : `src/components/ui/${file}`
}

function rewriteImports(source) {
  return source
    .replace(/from "cn"/g, 'from "@/lib/utils"')
    .replace(/@\/registry\/new-york-v4\/ui\//g, '@/components/ui/')
    .replace(/@\/registry\/new-york-v4\/lib\//g, '@/lib/')
}

const registry = {}
for (const name of ITEMS) {
  const res = await fetch(`${BASE}/${name}.json`)
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`)
  const item = await res.json()
  registry[name] = {
    dependencies: (item.dependencies ?? []).filter((d) => d !== 'cn'),
    registryDependencies: (item.registryDependencies ?? []).map((d) => d.split('/').pop()),
    files: item.files.map((f) => ({ path: targetPath(f.path), content: rewriteImports(f.content) })),
  }
  console.log(name.padEnd(10), JSON.stringify(registry[name].dependencies), JSON.stringify(registry[name].registryDependencies))
}

const outDir = new URL('../packages/library/src/shadcn/', import.meta.url)
await mkdir(outDir, { recursive: true })
await writeFile(
  new URL('registry.generated.ts', outDir),
  `// Generated by scripts/sync-shadcn.mjs from ${BASE} (shadcn/ui, MIT). Do not edit by hand.\n\n` +
    'export interface RegistryItem {\n  dependencies: string[]\n  registryDependencies: string[]\n  files: { path: string; content: string }[]\n}\n\n' +
    `export const SHADCN_REGISTRY: Record<string, RegistryItem> = ${JSON.stringify(registry, null, 2)}\n`,
)
console.log('wrote packages/library/src/shadcn/registry.generated.ts')
